# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-04-18 20:53:53
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # EV_Site_Selection_Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(extent="829460.713 806172.127 844974.799 817355.99 PROJCRS[\"Hong_Kong_1980_Grid\",BASEGEOGCRS[\"GCS_Hong_Kong_1980\",DATUM[\"D_Hong_Kong_1980\",ELLIPSOID[\"International_1924\",6378388.0,297.0]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",836694.05],PARAMETER[\"False_Northing\",819069.8],PARAMETER[\"Central_Meridian\",114.1785555555556],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",22.31213333333334]],CS[Cartesian,2],AXIS[\"Northing (Y)\",north,ORDER[1]],AXIS[\"Easting (X)\",east,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"2326\"]]", mask="C:\\Users\\wuruonan\\Documents\\ArcGIS\\Packages\\7305_TeamProject_Package_4525be\\p30\\..\\commondata\\hki_4districts_shp\\HKI_4districts.shp"):
        HKI_4districts_shp = fr"{arcpy.env.scriptWorkspace}\..\..\commondata\hki_4districts_shp\HKI_4districts.shp"
        CENTERLINE = "CENTERLINE"
        Hong_Kong_Island_4_Districts_4_ = "Hong Kong Island 4 Districts"
        Major_Roads_HKI = "Major_Roads_HKI"
        Major_Roads_HKI_2_ = "Major_Roads_HKI"
        EV_ChargingStation = "EV_ChargingStation"
        Hong_Kong_Island_4_Districts_2_ = "Hong Kong Island 4 Districts"
        Major_Roads_HKI_3_ = "Major_Roads_HKI"
        Final_Commercial_POI_HKIsland = "Final_Commercial_POI_HKIsland"
        Hong_Kong_Island_4_Districts_3_ = "Hong Kong Island 4 Districts"
        population_hki_hk80 = "population_hki_hk80"
        Hong_Kong_Island_4_Districts = "Hong Kong Island 4 Districts"
        Digital_Terrain_Model_tif = arcpy.Raster("Digital Terrain Model.tif")
        Hong_Kong_Island_4_Districts_6_ = "Hong Kong Island 4 Districts"
        C2_Reclass = arcpy.Raster(fr"{arcpy.env.scriptWorkspace}\..\..\commondata\phase2_analysis.gdb\C2_Reclass")
        C3_Charger_Dist = arcpy.Raster("C3_Charger_Dist")
        C4_Landuse_Raster_5m_tif = arcpy.Raster("C4_Landuse_Raster_5m.tif")
        Hong_Kong_Island_4_Districts_5_ = "Hong Kong Island 4 Districts"
        reclass_rule_csv = fr"{arcpy.env.scriptWorkspace}\..\..\commondata\teamwork\reclass_rule.csv"
        C5_Reclass = arcpy.Raster(fr"{arcpy.env.scriptWorkspace}\..\..\commondata\phase2_analysis.gdb\C5_Reclass")
        C6_Reclass = arcpy.Raster(fr"{arcpy.env.scriptWorkspace}\..\..\commondata\phase2_analysis.gdb\C6_Reclass")
        Scenario_A_EqualWeight_2_ = arcpy.Raster("Scenario_A_EqualWeight")

        # Process: Pairwise Clip (4) (PairwiseClip) (analysis)
        Roads_HKI_Clipped = fr"{arcpy.env.scratchGDB}\Roads_HKI_Clipped"
        arcpy.analysis.PairwiseClip(in_features=CENTERLINE, clip_features=Hong_Kong_Island_4_Districts_4_, out_feature_class=Roads_HKI_Clipped)

        # Process: Euclidean Distance (EucDistance) (sa)
        C1_Road_Dist = fr"{arcpy.env.scratchGDB}\C1_Road_Dist"
        Euclidean_Distance = C1_Road_Dist
        Output_direction_raster = ""
        Out_back_direction_raster = ""
        C1_Road_Dist = arcpy.sa.EucDistance(Major_Roads_HKI, None, "5", Output_direction_raster, "PLANAR", "", Out_back_direction_raster)
        C1_Road_Dist.save(Euclidean_Distance)


        # Process: Pairwise Clip (2) (PairwiseClip) (analysis)
        Chargers_HKI = fr"{arcpy.env.scratchGDB}\Chargers_HKI"
        arcpy.analysis.PairwiseClip(in_features=EV_ChargingStation, clip_features=Hong_Kong_Island_4_Districts_2_, out_feature_class=Chargers_HKI)

        # Process: Euclidean Distance (2) (EucDistance) (sa)
        C1_Road_Dist_3_ = fr"{arcpy.env.scratchGDB}\C1_Road_Dist"
        Euclidean_Distance_2_ = C1_Road_Dist_3_
        Output_direction_raster_2_ = ""
        Out_back_direction_raster_2_ = ""
        C1_Road_Dist_3_ = arcpy.sa.EucDistance(Chargers_HKI, None, "5", Output_direction_raster_2_, "PLANAR", "", Out_back_direction_raster_2_)
        C1_Road_Dist_3_.save(Euclidean_Distance_2_)


        # Process: Pairwise Clip (3) (PairwiseClip) (analysis)
        POI_HKI = fr"{arcpy.env.scratchGDB}\POI_HKI"
        arcpy.analysis.PairwiseClip(in_features=Final_Commercial_POI_HKIsland, clip_features=Hong_Kong_Island_4_Districts_3_, out_feature_class=POI_HKI)

        # Process: Euclidean Distance (3) (EucDistance) (sa)
        C6_POI_Dist = fr"{arcpy.env.scratchGDB}\C6_POI_Dist"
        Euclidean_Distance_3_ = C6_POI_Dist
        Output_direction_raster_3_ = ""
        Out_back_direction_raster_3_ = ""
        C6_POI_Dist = arcpy.sa.EucDistance(POI_HKI, None, "5", Output_direction_raster_3_, "PLANAR", "", Out_back_direction_raster_3_)
        C6_POI_Dist.save(Euclidean_Distance_3_)


        # Process: Pairwise Clip (PairwiseClip) (analysis)
        Population_HKI = fr"{arcpy.env.scratchGDB}\Population_HKI"
        arcpy.analysis.PairwiseClip(in_features=population_hki_hk80, clip_features=Hong_Kong_Island_4_Districts, out_feature_class=Population_HKI)

        # Process: Polygon to Raster (PolygonToRaster) (conversion)
        C2_Pop_Density = fr"{arcpy.env.scratchGDB}\C2_Pop_Density"
        arcpy.conversion.PolygonToRaster(in_features=Population_HKI, value_field="Pop_Den", out_rasterdataset=C2_Pop_Density)

        # Process: Reclassify (2) (Reclassify) (3d)
        Reclass_C2_P1 = fr"{arcpy.env.scratchGDB}\Reclass_C2_P1"
        arcpy.ddd.Reclassify(in_raster=C2_Pop_Density, reclass_field="VALUE", remap="129.084457 30911.752314 1;30911.752314 94097.228443 2;94097.228443 162143.125813 3;162143.125813 238289.725250 4;238289.725250 413264.889914 5", out_raster=Reclass_C2_P1)
        Reclass_C2_P1 = arcpy.Raster(Reclass_C2_P1)

        # Process: Extract by Mask (2) (ExtractByMask) (sa)
        DTM_HKI = fr"{arcpy.env.scratchGDB}\DTM_HKI"
        Extract_by_Mask_2_ = DTM_HKI
        DTM_HKI = arcpy.sa.ExtractByMask(Digital_Terrain_Model_tif, Hong_Kong_Island_4_Districts_6_, "INSIDE", "829460.713 806172.127 844974.799 817355.99 PROJCRS[\"Hong_Kong_1980_Grid\",BASEGEOGCRS[\"GCS_Hong_Kong_1980\",DATUM[\"D_Hong_Kong_1980\",ELLIPSOID[\"International_1924\",6378388.0,297.0]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",836694.05],PARAMETER[\"False_Northing\",819069.8],PARAMETER[\"Central_Meridian\",114.1785555555556],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",22.31213333333334]],CS[Cartesian,2],AXIS[\"Northing (Y)\",north,ORDER[1]],AXIS[\"Easting (X)\",east,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"2326\"]]")
        DTM_HKI.save(Extract_by_Mask_2_)


        # Process: Slope (Slope) (3d)
        C5_Slope = fr"{arcpy.env.scratchGDB}\C5_Slope"
        arcpy.ddd.Slope(in_raster=DTM_HKI, out_raster=C5_Slope, output_measurement="PERCENT_RISE")
        C5_Slope = arcpy.Raster(C5_Slope)

        # Process: Reclassify (4) (Reclassify) (3d)
        Reclass_C5_S1 = fr"{arcpy.env.scratchGDB}\Reclass_C5_S1"
        arcpy.ddd.Reclassify(in_raster=C5_Slope, reclass_field="VALUE", remap="0.001000 2 5;2 5 4;5 10 3;10 15 2;15 999 1", out_raster=Reclass_C5_S1)
        Reclass_C5_S1 = arcpy.Raster(Reclass_C5_S1)

        # Process: Reclassify (5) (Reclassify) (3d)
        Reclass_C6_P1 = fr"{arcpy.env.scratchGDB}\Reclass_C6_P1"
        arcpy.ddd.Reclassify(in_raster=C6_POI_Dist, reclass_field="VALUE", remap="0.001000 300 5;300 600 4;600 1000 3;1000 1500 2;1500 9999 1", out_raster=Reclass_C6_P1)
        Reclass_C6_P1 = arcpy.Raster(Reclass_C6_P1)

        # Process: Reclassify (Reclassify) (3d)
        C1_Reclass = fr"{arcpy.env.scratchGDB}\C1_Reclass"
        arcpy.ddd.Reclassify(in_raster=C1_Road_Dist_3_, reclass_field="VALUE", remap="0.000100 250 5;250 500 4;500 800 3;800 1100 2;1100 9999 1", out_raster=C1_Reclass)
        C1_Reclass = arcpy.Raster(C1_Reclass)

        # Process: Reclassify (3) (Reclassify) (3d)
        C3_Reclass = fr"{arcpy.env.scratchGDB}\C3_Reclass"
        arcpy.ddd.Reclassify(in_raster=C3_Charger_Dist, reclass_field="VALUE", remap="0.000100 150 1;150 300 2;300 500 3;500 800 4;800 9999 5", out_raster=C3_Reclass)
        C3_Reclass = arcpy.Raster(C3_Reclass)

        # Process: Extract by Mask (ExtractByMask) (sa)
        Landuse_HKI = fr"{arcpy.env.scratchGDB}\Landuse_HKI"
        Extract_by_Mask = Landuse_HKI
        Landuse_HKI = arcpy.sa.ExtractByMask(C4_Landuse_Raster_5m_tif, Hong_Kong_Island_4_Districts_5_, "INSIDE", "829460.713 806172.127 844974.799 817355.99 PROJCRS[\"Hong_Kong_1980_Grid\",BASEGEOGCRS[\"GCS_Hong_Kong_1980\",DATUM[\"D_Hong_Kong_1980\",ELLIPSOID[\"International_1924\",6378388.0,297.0]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",836694.05],PARAMETER[\"False_Northing\",819069.8],PARAMETER[\"Central_Meridian\",114.1785555555556],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",22.31213333333334]],CS[Cartesian,2],AXIS[\"Northing (Y)\",north,ORDER[1]],AXIS[\"Easting (X)\",east,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"2326\"]]")
        Landuse_HKI.save(Extract_by_Mask)


        # Process: Reclass by Table (ReclassByTable) (3d)
        C4_Reclass = fr"{arcpy.env.scratchGDB}\C4_Reclass"
        arcpy.ddd.ReclassByTable(in_raster=Landuse_HKI, in_remap_table=reclass_rule_csv, from_value_field="Code", to_value_field="Code", output_value_field="NewValue", out_raster=C4_Reclass, missing_values="NODATA")
        C4_Reclass = arcpy.Raster(C4_Reclass)

        # Process: Weighted Overlay (3) (WeightedOverlay) (sa)
        Scenario_C_Equity = fr"{arcpy.env.scratchGDB}\Scenario_C_Equity"
        Weighted_Overlay_3_ = Scenario_C_Equity
        Scenario_C_Equity = arcpy.sa.WeightedOverlay(WOTable([[C1_Reclass, 10 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [C2_Reclass, 25 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [C3_Reclass, 30 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [C4_Reclass, 8 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [C5_Reclass, 5 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [C6_Reclass, 22 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])]], [1, 5, 1]))
        Scenario_C_Equity.save(Weighted_Overlay_3_)


        # Process: Weighted Overlay (WeightedOverlay) (sa)
        Scenario_A_EqualWeight = fr"{arcpy.env.scratchGDB}\Weighte_C1_R1"
        Weighted_Overlay = Scenario_A_EqualWeight
        Scenario_A_EqualWeight = arcpy.sa.WeightedOverlay(WOTable([[C1_Reclass, 17 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C2_Reclass, 17 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C3_Reclass, 17 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C4_Reclass, 16 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C5_Reclass, 16 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C6_Reclass, 17 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])]], [1, 5, 1]))
        Scenario_A_EqualWeight.save(Weighted_Overlay)


        # Process: Focal Statistics (FocalStatistics) (ia)
        FocalMax_A = fr"{arcpy.env.scratchGDB}\FocalMax_A"
        Focal_Statistics = FocalMax_A
        FocalMax_A = arcpy.ia.FocalStatistics(Scenario_A_EqualWeight, "Circle 500 MAP", "MAXIMUM", "DATA", 90)
        FocalMax_A.save(Focal_Statistics)


        # Process: Raster Calculator (2) (RasterCalculator) (ia)
        Peaks_A_2_ = fr"{arcpy.env.scratchGDB}\Peaks_A"
        Raster_Calculator_2_ = Peaks_A_2_
        Peaks_A_2_ =  Con((Scenario_A_EqualWeight==FocalMax_A)&( Scenario_A_EqualWeight_2_==5),1) 
        Peaks_A_2_.save(Raster_Calculator_2_)


        # Process: Raster to Point (RasterToPoint) (conversion)
        CandidatePoints_A_all = fr"{arcpy.env.scratchGDB}\CandidatePoints_A_all"
        arcpy.conversion.RasterToPoint(in_raster=Peaks_A_2_, out_point_features=CandidatePoints_A_all)

        # Process: Sort (Sort) (management)
        Output_Dataset = fr"{arcpy.env.scratchGDB}\CandidatePoints_A_all_Sort"
        arcpy.management.Sort(in_dataset=CandidatePoints_A_all, out_dataset=Output_Dataset, sort_field=[])

        # Process: Weighted Overlay (2) (WeightedOverlay) (sa)
        Scenario_B_Transport = fr"{arcpy.env.scratchGDB}\Scenario_B_Transport"
        Weighted_Overlay_2_ = Scenario_B_Transport
        Scenario_B_Transport = arcpy.sa.WeightedOverlay(WOTable([[C1_Reclass, 30 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C2_Reclass, 10 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C3_Reclass, 10 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C4_Reclass, 7 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C5_Reclass, 5 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])], [C6_Reclass, 38 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 2], [4, 3], [5, 3], ['NODATA', 'NODATA']])]], [1, 5, 1]))
        Scenario_B_Transport.save(Weighted_Overlay_2_)


        # Process: Focal Statistics (3) (FocalStatistics) (ia)
        FocalMax_B = fr"{arcpy.env.scratchGDB}\FocalMax_B"
        Focal_Statistics_3_ = FocalMax_B
        FocalMax_B = arcpy.ia.FocalStatistics(Scenario_B_Transport, "Circle 500 MAP", "MAXIMUM", "DATA", 90)
        FocalMax_B.save(Focal_Statistics_3_)


        # Process: Raster Calculator (RasterCalculator) (ia)
        Peaks_B = fr"{arcpy.env.scratchGDB}\Peaks_B"
        Raster_Calculator = Peaks_B
        Peaks_B = 
        Peaks_B.save(Raster_Calculator)


        # Process: Raster to Point (2) (RasterToPoint) (conversion)
        Output_point_features = fr"{arcpy.env.scratchGDB}\RasterT_Peaks_B1"
        arcpy.conversion.RasterToPoint(in_raster=Peaks_B, out_point_features=Output_point_features)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="5", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", curveProcessingMethod="EXACT", maintainAttachments=True, 
                          maintainSpatialIndex=False, matchMultidimensionalVariable=True, nodata="NONE", 
                          outputCoordinateSystem="PROJCRS[\"Hong_Kong_1980_Grid\",BASEGEOGCRS[\"GCS_Hong_Kong_1980\",DATUM[\"D_Hong_Kong_1980\",ELLIPSOID[\"International_1924\",6378388.0,297.0]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",836694.05],PARAMETER[\"False_Northing\",819069.8],PARAMETER[\"Central_Meridian\",114.1785555555556],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",22.31213333333334]],CS[Cartesian,2],AXIS[\"Northing (Y)\",north,ORDER[1]],AXIS[\"Easting (X)\",east,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"2326\"]]", outputMFlag="Same As Input", outputZFlag="Same As Input", 
                          preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", qualifiedFieldNames=True, 
                          randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", resamplingMethod="NEAREST", 
                          scratchWorkspace="C:\\ArcGIS\\Packages\\EV_Model_Project_db543b\\commondata\\7305_teamproject.gdb", terrainMemoryUsage=False, tileSize="128 128", 
                          tinSaveVersion="CURRENT", transferDomains=False, transferGDBAttributeProperties=False, 
                          unionDimension=False, workspace="..\\7305_TeamProject.gdb"):
        Model()
